### ISSUE TITLE
Don't know proper LDAP_DEBUG option for this SDK.

### ISSUE THREAD

**Issue by charlescva** [covener/apache-modules#1]
Hi.  I am not very familiar with C++ but I have compiled a few different things in the past with success.

I am trying to debug an internal server 500 error on httpd 2.2.26 when a user is prompted for LDAP credentials and enters the correct credentials.

I compiled apache 2.2.31, and used apxs to compile the shared module.  When running, 'httpd -M' it shows the module is loaded and putting "LDAPDebugLevel 7" in the global scope, results in the following message in my debug/error_log:

```
[Tue Oct 25 16:42:13 2016] [info] APR LDAP: Built with OpenLDAP LDAP SDK
[Tue Oct 25 16:42:13 2016] [info] LDAP: SSL support available
**[Tue Oct 25 16:42:13 2016] [debug] mod_ldap_debug.c(60): ldap_debug_module: Don't know proper LDAP_DEBUG option for this SDK.**
[Tue Oct 25 16:42:13 2016] [notice] Apache/2.2.26 (Unix) mod_ssl/2.2.26 OpenSSL/1.0.1e-fips PHP/5.3.3 configured -- resuming normal operations
```

At this point, even when triggering the 500 error, there are not messages in the error_log from mod_ldap_debug.  Any help would be appreciated.

CentOS 6.8 w/ HTTPd 2.2.26

Thanks,
Charles

**Comment by covener** [comment]
Hi Charles, can you share the output from the system where you compiled the module:

> grep debug /usr/include/ldap.h

On my system at the time I must have written this module, and currently, there is a #define for the debug level in openldap:

> #define LDAP_OPT_DEBUG_LEVEL            0x5001  /\* debug level */

The absence at compile time is triggering that message and basically no-op'ing the mod_ldap_debug.

**Comment by charlescva** [comment]
When I compiled the module, On my debian workstation, I downloaded the httpd-2.2 source, compiled httpd, then used the resultant /bin/apxs to compile the module, so there is no /usr/include/ldap.h on my system.  Perhaps here in lies the problem.

Additionally the test environment I'm using which has the 500 error does not have apxs installed for security reasons, so i sort of need to compile the shared module outside the environment, and then scp it in.

I am running a container with centos 6.8 now, and did an yum install of gcc, httpd, httpd-devel, openldap-devel.  It looks like grep debug /usr/include/ldap.h matches your #define output above.  I'll try compiling the module with apxs inside this container and ship it over to the test environment and let you know what happens.

Thanks so much for the speedy response!

**Comment by charlescva** [comment]
It works... But I think I'm confused even more now.  Because the Internal Server 500 error is no longer happening...

```
[Tue Oct 25 17:35:03 2016] [info] APR LDAP: Built with OpenLDAP LDAP SDK
[Tue Oct 25 17:35:03 2016] [info] LDAP: SSL support available
**[Tue Oct 25 17:35:03 2016] [debug] mod_ldap_debug.c(65): ldap_debug_module: setting debug parms in LDAP library to 7**

```

Now I have a VERY long debug log showing the ldap requests, responses, etc.  It is very long and looks like there are SEVERAL connections being attempted.  Some say Connected, while others say 

`merged parent (id 2) error info:  result errno 1, error <000004DC: LdapErr: DSID-0C0906DC, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v1db0>, matched <>`

But the httpd reverse proxy is now authenticating correctly and passing back the response from the application server?!   How would simply including this debug module fix things?  I have puppet so I'm going to roll it back to the original config, I may have changed something else that fixed it...

Thanks again so much this is a very valuable resource to have for troubleshooting LDAP on Httpd 2.2 (which is still supported by redhat on RHEL btw!)

**Comment by covener** [comment]
I agree, it shouldn't solve anything, just get you some lower level context for existing error messages.  Only thing I can imagine is that maybe you're loading a different libldap.so (or whatever) after doing something on that system.

**Comment by charlescva** [comment]
So I've verified that I get Server Internal Error 500 with this:

```
#  LoadModule ldap_debug_module modules/mod_ldap_debug.so
# LDAPDebugLevel 7

```

Then if I just remove the hashtags (uncomment), restart httpd... The internal server 500 error is gone and it works!?  I know this issue thread is not specific to httpd support, but since your module 'fixes' it, I was hoping you might have some insight.

Modules in use are:

```
  LoadModule ssl_module modules/mod_ssl.so
  LoadModule alias_module modules/mod_alias.so
  LoadModule filter_module modules/mod_filter.so
  LoadModule authz_host_module modules/mod_authz_host.so
  LoadModule authz_user_module modules/mod_authz_user.so
  LoadModule log_config_module modules/mod_log_config.so
  LoadModule logio_module modules/mod_logio.so
  LoadModule deflate_module modules/mod_deflate.so
  LoadModule headers_module modules/mod_headers.so
  LoadModule substitute_module modules/mod_substitute.so
  LoadModule rewrite_module modules/mod_rewrite.so
  LoadModule proxy_module modules/mod_proxy.so
  LoadModule proxy_http_module modules/mod_proxy_http.so
  LoadModule proxy_ajp_module modules/mod_proxy_ajp.so
  LoadModule mime_module modules/mod_mime.so
  LoadModule dir_module modules/mod_dir.so
  LoadModule auth_cas_module modules/mod_auth_cas.so
  LoadModule expires_module modules/mod_expires.so
  LoadModule setenvif_module modules/mod_setenvif.so
  LoadModule env_module modules/mod_env.so
  LoadModule php5_module modules/libphp5.so
  AddType application/x-httpd-php .php
  AddType application/x-httpd-php-source .phps
  LoadModule proxy_balancer_module modules/mod_proxy_balancer.so
  LoadModule auth_basic_module modules/mod_auth_basic.so
  LoadModule ldap_module modules/mod_ldap.so
  LoadModule authnz_ldap_module modules/mod_authnz_ldap.so
  LoadModule authn_file_module modules/mod_authn_file.so
```

**Comment by covener** [comment]
How about ldd of the compiled  mod_ldap_debug vs. lsof of the process w/o mod_ldap_debug loaded? Do they show different LDAP libraries maybe?

**Comment by charlescva** [comment]
ldd of the compiled mod_ldap_debug:

```
root@b4-web ~]$ ldd /usr/lib64/httpd/modules/mod_ldap_debug.so                                                   
        linux-vdso.so.1 =>  (0x00007ffd5c90c000)
        libc.so.6 => /lib64/libc.so.6 (0x00007f8da89d6000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f8da8f72000)
```

**VS**

lsof of the process w/o mod_ldap_debug loaded:

```
root@b4-web ~]$ lsof -p 32104 | grep .so | grep '/ld-linux\|/libc\|/linux-vdso'
httpd   32104 root  mem    REG   253,1   347536    4060 /usr/lib64/libcurl.so.4.1.1
httpd   32104 root  mem    REG   253,1    14664    6892 /lib64/libcom_err.so.2.1
httpd   32104 root  mem    REG   253,1  1967392    3685 /usr/lib64/libcrypto.so.1.0.1e
httpd   32104 root  mem    REG   253,1  1924768    1933 /lib64/libc-2.12.so
httpd   32104 root  mem    REG   253,1    40872    7361 /lib64/libcrypt-2.12.so
```

If I am understanding this analysis correctly, perhaps the issue is that libc.so.6 includes the correct code and libc-2.12 does not?  Or perhaps ld-linux-x86-64.so.2 or linux-vdso.so.1 need to be included on the LD_LIBRARY_PATH for httpd?

**EDIT: Well they are the same..**

```
root@b4-web /]$ md5sum /lib64/libc.so.6
14486c78922a8dc8376a715d4c78d85a  /lib64/libc.so.6
root@b4-web /]$ md5sum /lib64/libc-2.12.so
14486c78922a8dc8376a715d4c78d85a  /lib64/libc-2.12.so
```

Also, the only module loaded is yours... I dumped lsof to two files, used sed so the PIDs would match, and did a diff:

```
root@b4-web /]$ diff ldap_debug_enabled ldap_debug_disabled 
35d34
< httpd   13143 root  mem    REG   253,1    19006    9552 /usr/lib64/httpd/modules/mod_ldap_debug.so
root@b4-web /]$ cat ldap_debug_enabled | wc -l
103
root@b4-web /]$ cat ldap_debug_disabled | wc -l
102
```
